# Oefeningen basis Python

Importeer de volgende bibliotheken: math, numpy en pandas

In [1]:
import pandas as pd
import math as math
import numpy as np

## Lijsten en tabellen

Maak een list met volgende waarden: 1, 2, 3, 4, 5 en stop deze in de variabele "id"

In [2]:
lijst = [1,2,3,4,5]
id = pd.Series(lijst)
print(id)

0    1
1    2
2    3
3    4
4    5
dtype: int64


Maak een numpy array met volgende waarden: 15, 18, 11, 17, 20 en stop deze in de variabele "leeftijd"

In [3]:
lijst = [15,18,11,17,20]
leeftijd = np.array(lijst)
print(leeftijd)

[15 18 11 17 20]


Zet de waarden van "leeftijd" om naar een pandas Series en zet het resultaat terug in de variabele "leeftijd".  Verifieer dat het type klopt.

In [4]:
leeftijd = pd.Series(leeftijd)
print(leeftijd)

0    15
1    18
2    11
3    17
4    20
dtype: int32


Maak een list met volgende waarden: 54.2, 68.1, 41.7, 59.5, 65.4 en stop deze in de variabele "gewicht"

In [5]:
gewicht = [54.2,68.1,41.7,59.5,65.4]

Maak een numpy array met volgende waarden: 36.5, 37.1, 36.4, 37.2, 36.9 en stop deze in de variabele "temp"

In [6]:
lijst = [36.5,37.1,36.4,37.2,36.9]
temp = np.array(lijst)
print(lijst)

[36.5, 37.1, 36.4, 37.2, 36.9]


Zet de array "temp" om naar een list en bewaar het resultaat terug in "temp".  Verfifieer dat het type nu wel degelijk een list is.

In [7]:
lijst = list(temp)
print(temp)

[36.5 37.1 36.4 37.2 36.9]


Maak een tabel (data frame) waarin de vorige lijsten de kolommen vormen en stop deze in de variabele "gegevens".  Gebruik voor de namen van de kolommen de namen van de variabelen ("id", "leeftijd", "gewicht" en "temp").

In [8]:
frame = pd.DataFrame({"id":id,"leeftijd":leeftijd,"gewicht":gewicht,"temp":temp})
print(frame)

   id  leeftijd  gewicht  temp
0   1        15     54.2  36.5
1   2        18     68.1  37.1
2   3        11     41.7  36.4
3   4        17     59.5  37.2
4   5        20     65.4  36.9


Toon de kolomnamen van de tabel

In [9]:
print("kolomnamen: ", frame.columns.to_list())

kolomnamen:  ['id', 'leeftijd', 'gewicht', 'temp']


Toon het aantal kolommen

In [10]:
print("aantal kollomen: ", frame.columns.size)

aantal kollomen:  4


Toon de kolom met naam 'temp'

In [11]:
print(frame.temp)

0    36.5
1    37.1
2    36.4
3    37.2
4    36.9
Name: temp, dtype: float64


Toon de 2e kolom uit de tabel zonder de naam te gebruiken

In [12]:
print(frame.iloc[:,1])

0    15
1    18
2    11
3    17
4    20
Name: leeftijd, dtype: int32


Verwijder de derde rij uit de tabel

In [13]:
frame = frame.drop(3)
print(frame)

   id  leeftijd  gewicht  temp
0   1        15     54.2  36.5
1   2        18     68.1  37.1
2   3        11     41.7  36.4
4   5        20     65.4  36.9


Toon de 3e rij uit de tabel

In [14]:
print(frame.iloc[3])

id           5.0
leeftijd    20.0
gewicht     65.4
temp        36.9
Name: 4, dtype: float64


Toon de 2e en de 4e rij uit de tabel

In [15]:
print(frame.iloc[1])
print(frame.iloc[3])

id           2.0
leeftijd    18.0
gewicht     68.1
temp        37.1
Name: 1, dtype: float64
id           5.0
leeftijd    20.0
gewicht     65.4
temp        36.9
Name: 4, dtype: float64


Toon de 2e tot en met 4e rij uit de tabel

In [16]:
print(frame.iloc[1:4])

   id  leeftijd  gewicht  temp
1   2        18     68.1  37.1
2   3        11     41.7  36.4
4   5        20     65.4  36.9


Bereken de minimum en maximum leeftijd.  Je kan dit doen door de methoden "min()" en "max()" op te roepen op de kolom.

In [17]:
print("minimum leeftijd: ",frame.leeftijd.min())
print("maximum leeftijd: ",frame.leeftijd.max())

minimum leeftijd:  11
maximum leeftijd:  20


Bereken de som van alle gewichten en deel die door het aantal gewichten (bereken dus het gemiddelde gewicht).  Je kan hiervoor de methode "sum()" oproepen op de kolom.  De lengte van de kolom vind je met de functie "len()".
Bemerk dat sum() een methode is die je op een object oproept (de kolom) en len() een functie is die niet aan een object gekoppeld is (vergelijkbaar met een static method in java).  Dit laat zien dat Python een hybride taal is waarin je tegelijk OO en procedureel kan programmeren.
Toon het resultaat met 3 cijfers na de komma.  Hier zie je een hint hoe je dat kan doen:
```python
print("pi is{:10.2f}".format(math.pi))
```

In [18]:
print("gemiddelde gewicht: ",(frame.gewicht.sum()/ len(frame)))

gemiddelde gewicht:  57.35


Bereken alle gewichten in gram (vermenigvuldig ze dus met 1000) maar verander de tabel niet.  Geef het resultaat weer als een Python list.
Zie je wat er met de laatste waarde gebeurt?  Hoe komt dit?

In [19]:
gewichtLijst = list()
for i in frame.gewicht:
    gewichtLijst.append(i*1000)
print(gewichtLijst)

[54200.0, 68100.0, 41700.0, 65400.00000000001]


Zet alle temperaturen om naar Fahrenheit, rondt deze af op 1 cijfer na de komma en zet deze waarden in de tabel in een nieuwe kolom met de naam "temp_far".
Hint: een kolom uit een data frame is een Series en heeft een methode "round()"

In [20]:
farList = list()
for i in frame.temp:
    far=i *(9/5)+32
    farList.append(far)
frame["temp_far"]=farList
print(frame)

   id  leeftijd  gewicht  temp  temp_far
0   1        15     54.2  36.5     97.70
1   2        18     68.1  37.1     98.78
2   3        11     41.7  36.4     97.52
4   5        20     65.4  36.9     98.42


Volgende code bewaart de tabel in een bestand "gegevens.csv".  Voer deze gewoon uit en kijk waar het bestand bewaard werd:

In [21]:
frame.to_csv("gegevens.csv", sep=";", decimal=",", index=False)
# hijd zet dit in de durectory van het project

Open de tabel in excel of open office. Als je het bestand juist bewaard hebt, zou dit moeten lukken.  Je kan het bestand eventueel ook uploaden naar google drive en openen met google spreadheets.
Voeg er een kolom aan toe met de naam "extra".  Zet volgende gegevens in de kolom: "hallo", "dit", "is", "een", "testje"
Bewaar het bestand als csv.

Lees de aangepaste tabel nu terug in met volgende code en kijk na of de nieuwe kolom goed werd ingelezen:

In [22]:
gegevens = pd.read_csv("gegevens.csv", sep=";", decimal=",", header=0)

print(gegevens)

   id  leeftijd  gewicht  temp  temp_far
0   1        15     54.2  36.5     97.70
1   2        18     68.1  37.1     98.78
2   3        11     41.7  36.4     97.52
3   5        20     65.4  36.9     98.42


Verwijder de kolom “id”.

In [23]:
gegevens=gegevens.drop(columns='id')
print(gegevens)

   leeftijd  gewicht  temp  temp_far
0        15     54.2  36.5     97.70
1        18     68.1  37.1     98.78
2        11     41.7  36.4     97.52
3        20     65.4  36.9     98.42


Voeg een rij toe met [ 30, 74.1, 36.5, 97.7 ] als waarden (zoek eens op hoe je dat kan doen)

In [24]:
# hier komt jouw code
tempList = [30,74.1,36.5,97.7]
gegevens=gegevens.append(pd.DataFrame([tempList], columns=["leeftijd","gewicht","temp","temp_far"]),ignore_index=True)
print(gegevens)

   leeftijd  gewicht  temp  temp_far
0        15     54.2  36.5     97.70
1        18     68.1  37.1     98.78
2        11     41.7  36.4     97.52
3        20     65.4  36.9     98.42
4        30     74.1  36.5     97.70


<ipython-input-24-79367d060634>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gegevens=gegevens.append(pd.DataFrame([tempList], columns=["leeftijd","gewicht","temp","temp_far"]),ignore_index=True)


Voeg een kolom “lengte” toe met gegevens: 160, 175, 162, 169, 179

In [25]:
gegevens["lengte"]=[160,175,162,169,179]
print(gegevens)

   leeftijd  gewicht  temp  temp_far  lengte
0        15     54.2  36.5     97.70     160
1        18     68.1  37.1     98.78     175
2        11     41.7  36.4     97.52     162
3        20     65.4  36.9     98.42     169
4        30     74.1  36.5     97.70     179


Bereken de BMI van iedere persoon in de tabel en rond deze af op 1 cijfer na de komma.
De BMI is gelijk aan het gewicht gedeeld door de lengte in het kwadraat.  De lengte moet in meter uitgedrukt zijn en het gewicht in kilogram.
Het resultaat moet een list zijn.

In [26]:
BMIlist = list()
counter = 0
for i in gegevens.lengte:
    lengteM=i/100
    BMI = gegevens.gewicht[counter]/(lengteM*lengteM)
    counter += 1
    BMI = round(BMI,1)
    BMIlist.append(BMI)
print(BMIlist)

[21.2, 22.2, 15.9, 22.9, 23.1]


Voeg deze BMI als kolom toe aan de tabel.

In [27]:
gegevens["BMI"] = BMIlist
print(gegevens)

   leeftijd  gewicht  temp  temp_far  lengte   BMI
0        15     54.2  36.5     97.70     160  21.2
1        18     68.1  37.1     98.78     175  22.2
2        11     41.7  36.4     97.52     162  15.9
3        20     65.4  36.9     98.42     169  22.9
4        30     74.1  36.5     97.70     179  23.1


Toon alle gewichten die kleiner of gelijk zijn aan 60 uit de kolom gewicht als een list.

In [28]:
lengteList = list()
for i in gegevens.gewicht:
    if i <= 60:
        lengteList.append(i)
print(lengteList)

[54.2, 41.7]


Vervang in de kolom leeftijd alle leeftijden groter of gelijk aan 18 door 19.
Krijg je een warning?  Je kan dit oplossen door gegevens.loc[] te gebruiken.

In [29]:
rijen = gegevens.leeftijd >= 18
gegevens.loc[rijen,'leeftijd']=19
print(gegevens)

   leeftijd  gewicht  temp  temp_far  lengte   BMI
0        15     54.2  36.5     97.70     160  21.2
1        19     68.1  37.1     98.78     175  22.2
2        11     41.7  36.4     97.52     162  15.9
3        19     65.4  36.9     98.42     169  22.9
4        19     74.1  36.5     97.70     179  23.1


Vind alle temperaturen van de personen die ouder zijn dan 16 jaar.  Geef het resultaat weer als een numpy array.

In [30]:
rijen = gegevens.leeftijd > 16
numparr = np.array(gegevens.loc[rijen,'temp'])
print(numparr)

[37.1 36.9 36.5]


## Sport data

Lees het bestand "sportData.csv" in met volgende code.
Toon alle kolommen van de tabel, samen met hun type.

In [31]:
sport = pd.read_csv("sportData.csv", sep=";", decimal=",", header=0)
print(sport,"\n",sport.dtypes)
# sport.info()

    leeftijd geslacht      sport  keer per week  uren per week
0         12        m       geen              0            0.0
1         12        m  basketbal              1            2.0
2         13        m    voetbal              2            4.0
3         11        v    voetbal              2            4.0
4         13        v       geen              0            0.0
..       ...      ...        ...            ...            ...
70        12        v     turnen              2            4.0
71        11        v       judo              2            4.0
72        11        v    voetbal              1            NaN
73        12        v       geen              0            0.0
74        11        v     anders              1            2.0

[75 rows x 5 columns] 
 leeftijd           int64
geslacht          object
sport             object
keer per week      int64
uren per week    float64
dtype: object


Hoeveel data-rijen zijn er in dit bestand?

In [32]:
print("aantal rijen: ",len(sport))

aantal rijen:  75


Bepaal alle mogelijke waarden die in de kolom "sport" voorkomen.

In [33]:
sport.sport.unique()

array(['geen', 'basketbal', 'voetbal', 'klimmen', 'turnen', 'anders',
       'zwemmen', 'judo', 'fitness', nan], dtype=object)

Wat is het maximum van kolom "leeftijd"?

In [34]:
print("de maximum leeftijd is: ",sport.leeftijd.max())

de maximum leeftijd is:  14


Wat is de som van alle waarden van kolom "keer per week" die groter zijn dan 1?

In [35]:
rijen = sport['keer per week'] > 1
print("de som is: ",rijen.sum())

de som is:  37


Geef een lijst van alle sporten die beoefend worden door mensen die meer dan 3 keer per week sporten.  Geef het resultaat als een Series.

In [36]:
rijen = sport['keer per week'] >= 3
sportlist = list(sport.loc[rijen,'sport'])
print(sportlist)

['voetbal', 'voetbal', 'klimmen', 'judo', 'judo', 'basketbal', 'voetbal', 'fitness', 'fitness', 'basketbal', 'voetbal', 'judo', 'judo', 'basketbal', 'anders']


## Programmeren

Hier staan een aantal programmeeropdrachten om gewoon te raken aan de syntax en mogelijkheden van Python. Het is bedoeld voor de studenten die ook geïnteresseerd zijn in het programmeren zelf.

### Dobbelsteen
Schrijf een programma dat 6000 keer met de dobbelsteen rolt en telt hoeveel keer iedere waarde voorkomt.  Probeer geen lussen te moeten schrijven.  Je kan dit doen door te starten met een numpy array van 6000 willekeurige getallen tussen 1 en 6.

Voorbeeld van de werking (dit kan afwijken omdat het willekeurige getallen zijn, maar alle getallen zouden rond de 1000 moeten liggen):

```{text}
Aantal enen: 1007
Aantal tweeën: 994
Aantal drieën: 1006
Aantal vieren: 995
Aantal vijven: 998
Aantal zessen: 1000
```

In [37]:
i =0
een=0
twee=0
drie=0
vier=0
vijf=0
zes=0
while i < 6000:
    arr = np.random.randint(1,7)
    if arr == 1:
        een = een+1
    elif arr == 2:
        twee = twee +1
    elif arr == 3:
        drie = drie +1
    elif arr == 4:
        vier = vier +1
    elif arr == 5:
        vijf= vijf +1
    elif arr == 6:
        zes = zes +1
    i = i+1
print("aantal keer een: ", een)
print("aantal keer twee: ", twee)
print("aantal keer drie: ",drie)
print("aantal keer vier: ",vier)
print("aantal keer vijf: ",vijf)
print("aantal keer zes: ",zes)

aantal keer een:  1013
aantal keer twee:  967
aantal keer drie:  967
aantal keer vier:  1055
aantal keer vijf:  1011
aantal keer zes:  987


### Kerstboom

Schrijf een programma om een kerstboom af te drukken met behulp van ‘*’ tekens. De breedte van de boom wordt als een oneven geheel getal (13..29)  ingegeven. Indien niet voldaan is aan deze voorwaarde wordt de breedte op 13 ingesteld.

Eerst moet je het midden van de boom bepalen aan de hand van de breedte.
Vervolgens druk je de boom regel per regel af.
Opmerking: de stam bestaat altijd uit 4 regels met een breedte van 3.
Gebruik een for-lus om de boom af te drukken.

Je kan het getal inlezen met volgende code:
```{python}
breedte = int(input("Geef de breedte de van kerstboom (oneven getal in bereik 13..29):"))
```
Als je iets wil printen zonder newline op het einde (zoals System.out.print() in Java), dan kan dat als volgt:
```{python}
print("hello, ", end='')
print("world!")
```
Je kan een aantal keer hetzelfde karakter in een string zetten met:
```{python}
karakter = "*"
aantal = 5
print(karakter * aantal)
```

Voorbeeld van de werking:

```{text}
Geef de breedte de van kerstboom (oneven getal in bereik 13..29): 13

      *
     ***
    *****
   *******
  *********
 ***********
*************
     ***
     ***
     ***
     ***
```

In [3]:
# hier komt jouw code
i = 0
staramount = 1
while i <= 5:
    print("*"*staramount)
    staramount = staramount+2
    print("\n")
    i=i+1

*


***


*****


*******


*********


***********




### Geheim schrift
Schrijf een programma om berichten te coderen en te decoderen zoals Julius Caesar deed.
Het programma vraagt eerst een bericht.  Dit bericht wordt naar hoofdletters omgezet.
Daarna vraagt het programma aan de gebruiker of het bericht gecodeerd of gedecodeerd moet worden.
Om te coderen, doorloopt het programma alle letters in het bericht en verschuift deze letter telkens een aantal plaatsen (zet deze verschuiving in een variabele).
Met een verschuiving van 3 wordt bijvoorbeeld de letter 'A' een 'D'.  Indien je aan het einde van het alfabet komt begin je terug bij de 'A' (een 'Z' wordt in dit geval een 'C'). Bij het decoderen doe je uiteraard het tegenovergestelde.  Je kan dit heel snel doen door gebruik te maken van de ASCII code van ieder karakter (je mag ervan uitgaan dat alle karakters in de ASCII set passen).
Als een karakter geen letter is, dan wordt die gewoon ongecodeerd (of ongedecodeerd) weergegeven.

Voorbeeld van werking (de verschuiving staat hier op 6):
```{text}
Geef een bericht: The quick brown fox jumps over the lazy dog.
Wil je dit encoderen? J
Gecodeerd bericht:
ZNK WAOIQ HXUCT LUD PASVY UBKX ZNK RGFE JUM.

Geef een bericht: ZNK WAOIQ HXUCT LUD PASVY UBKX ZNK RGFE JUM.
Wil je dit encoderen? N
Gedecodeerd bericht:
THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG.
```
Hint: je kan de code heel compact maken als je gebruik maakt van de modulo (%) operator.
Hint: je kan een karakter omzetten naar zijn ASCII code met "ord(c)" en omgekeerd kan je een ASCII code naar een karakter omzetten met "chr(code)"

In [39]:
# hier komt jouw code

### Vervangen
Maak een functie "vervang(lijst, te_zoeken, vervanging)" die in een list op zoek gaat naar een waarde en die vervangt door een andere.

In [40]:
# hier komt jouw code

Test de functie uit door in de list [ 10, 20, 30, 30, 40, 30, 0 ] de waarde 30 te vervangen door 42.
Probeer of je functie ook werkt op een numpy array en een pandas Series.  Dat zou moeten lukken.

In [41]:
# hier komt jouw code

### Wachtwoorden
Een goed wachtwoord kiezen, is voor sommige gebruikers een ware opgave.  We willen een programma maken waarin de gebruiker een nieuw wachtwoord moet kiezen.  Dit moet (omdat we het graag ingewikkeld maken) minstens 8 karakters lang zijn, minstens 1 hoofdletter, 1 kleine letter, een cijfer en een leesteken bevatten.
Maak een functie "is_goed_wachtwoord" die een wachtwoord als parameter meekrijgt en een boolean teruggeeft.  Die boolean is true als het gegeven wachtwoord voldoet aan alle eisen.  De functie geeft ook een foutmelding op het scherm als het wachtwoord niet goed is.
Maak dan een programma dat een nieuw wachtwoord vraagt totdat alle eisen voldaan zijn.

Voorbeeld van de werking:

```{text}
Geef een nieuw wachtwoord: ww
Het moet minstens 8 karakters lang zijn
Geef een nieuw wachtwoord: wachtwoord
Het moet minstens 1 hoofdletter bevatten
Geef een nieuw wachtwoord: WACHTWOORD
Het moet minstens 1 kleine letter bevatten
Geef een nieuw wachtwoord: Wachtwoord
Het moet minstens 1 cijfer bevatten
Geef een nieuw wachtwoord: Wachtw00rd
Het moet minstens 1 leesteken bevatten
Geef een nieuw wachtwoord: Wachtw00rd!
Je nieuwe wachtwoord is goedgekeurd!
```

Hint: je kan heel eenvoudig itereren door de karakters van een string met:
```{python}
for c in string:
    ...
```

In [42]:
# hier komt jouw code